# Generated by Django 6.0.1 on 2026-01-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='discount_percentage',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(default='Акция', max_length=100),
        ),
    ]
