# Generated by Django 6.0.1 on 2026-01-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_alter_promotion_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='product',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='start_date',
        ),
        migrations.AddField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_percentage',
            field=models.PositiveIntegerField(verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название акции'),
        ),
    ]
