# Generated by Django 6.0.1 on 2026-01-23 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('promotions', '0003_remove_promotion_product_remove_promotion_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='core.product', verbose_name='Выберите товар'),
            preserve_default=False,
        ),
    ]
